### ISSUE TITLE
[AutoClicker] Does not detect clicks 

### ISSUE THREAD

**Issue by UnEnanoMas** [Blackjack200/Lunar#8]
https://streamable.com/xqn1yn

The specter could be added but every time you add one it gives you an error as I have already reported in #7 

The autoclicker is not being detected by Lunar

(The messages that appear at the top left are messages from a CPS plugin that alerts me when someone reaches more than 15 fps)

Lunar: Dev 31
PMMP: 3.19.0
OS: Linux
PHP: 7.4
Minecraft: 1.16.220

**Comment by Blackjack200** [comment]
see config.yml
```yaml
AutoClicker:
  Enable: true
  Punishment: BAN
  # Max CPS
  MaxCPS: 25
  MaxVL: 5
  Reward: 0.988
```

**Comment by UnEnanoMas** [comment]
```yaml

AutoClicker:
  Enable: true
  Punishment: BAN
  # Max CPS
  MaxCPS: 25
  MaxVL: 5
  Reward: 0.988

```
  
Got the same
Edit: I have tried it with another account that I have and it does not detect it or ban it
